"""
pdf_exporter.py - Generates official Court-Ready PDF Incident Reports for Face Seeker.
"""

import os
import sys
from datetime import datetime
from fpdf import FPDF


def sanitize_str(text: str) -> str:
    """Sanitize unicode characters to Latin-1 range for standard FPDF fonts."""
    if not text:
        return ""
    replacements = {
        "’": "'",
        "‘": "'",
        "“": '"',
        "”": '"',
        "–": "-",
        "—": "-",
        "•": "-",
        "…": "...",
    }
    for orig, repl in replacements.items():
        text = text.replace(orig, repl)
    return text.encode("latin-1", "replace").decode("latin-1")


class IncidentReportPDF(FPDF):
    def header(self):
        self.set_fill_color(32, 32, 32)  # Win11 Dark Banner
        self.rect(0, 0, 210, 24, "F")
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(255, 255, 255)
        self.cell(0, 10, "  OFFICIAL INCIDENT REPORT: TARGET FACE MATCHES", ln=True, align="L")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(173, 173, 173)
        self.cell(0, 4, sanitize_str(f"  Generated by Face Seeker Target Face Detector  |  Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"), ln=True, align="L")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}  -  CONFIDENTIAL & PROPRIETARY", align="C")


def generate_pdf_report(target_image_path: str, video_path: str, matches: list, output_pdf_path: str) -> bool:
    """
    Generate structured PDF report of detected target matches.
    """
    try:
        pdf = IncidentReportPDF()
        pdf.alias_nb_pages()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)

        # Section 1: Source & Target Information
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(0, 120, 212) # Win11 Accent Blue
        pdf.cell(0, 8, "1. Video & Target Metadata", ln=True)
        pdf.set_line_width(0.5)
        pdf.set_draw_color(0, 120, 212)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(3)

        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(30, 30, 30)

        video_fname = sanitize_str(os.path.basename(video_path)) if video_path else "N/A"
        target_fname = sanitize_str(os.path.basename(target_image_path)) if target_image_path else "N/A"

        pdf.cell(95, 6, sanitize_str(f"Source Video File: {video_fname}"), ln=False)
        pdf.cell(95, 6, sanitize_str(f"Target Image File: {target_fname}"), ln=True)
        pdf.cell(95, 6, sanitize_str(f"Total Matches Found: {len(matches)}"), ln=False)
        highest_score = max([m.get('score', 0) for m in matches]) * 100.0 if matches else 0.0
        pdf.cell(95, 6, sanitize_str(f"Highest Match Score: {highest_score:.1f}%"), ln=True)
        pdf.ln(6)

        # Section 2: Matches Table
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(0, 120, 212)
        pdf.cell(0, 8, "2. Match Event Log", ln=True)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(4)

        # Table Header
        pdf.set_fill_color(43, 43, 43)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(20, 7, "Match #", border=1, align="C", fill=True)
        pdf.cell(40, 7, "Timestamp (HH:MM:SS)", border=1, align="C", fill=True)
        pdf.cell(35, 7, "Frame Number", border=1, align="C", fill=True)
        pdf.cell(45, 7, "Similarity Score", border=1, align="C", fill=True)
        pdf.cell(50, 7, "Bounding Box (XYWH)", border=1, align="C", fill=True)
        pdf.ln()

        # Table Rows
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(30, 30, 30)

        for idx, match in enumerate(matches, 1):
            fill_bg = (idx % 2 == 0)
            if fill_bg:
                pdf.set_fill_color(240, 240, 240)
            else:
                pdf.set_fill_color(255, 255, 255)

            score_pct = match.get('score', 0.0) * 100.0
            bbox_str = str(match.get('bbox', 'N/A'))

            pdf.cell(20, 7, str(idx), border=1, align="C", fill=fill_bg)
            pdf.cell(40, 7, sanitize_str(str(match.get('timestamp_str', '00:00:00'))), border=1, align="C", fill=fill_bg)
            pdf.cell(35, 7, str(match.get('frame_idx', 0)), border=1, align="C", fill=fill_bg)
            pdf.cell(45, 7, f"{score_pct:.2f}%", border=1, align="C", fill=fill_bg)
            pdf.cell(50, 7, sanitize_str(bbox_str), border=1, align="C", fill=fill_bg)
            pdf.ln()

        pdf.output(output_pdf_path)
        return True
    except Exception as e:
        print(f"PDF Export Error: {e}")
        return False
